### PR TITLE
Implement feature for Issue  #149

### PR DESCRIPTION
**Pull request by christopher-conley**
This PR implements the feature request in Issue [#149](https://github.com/liftoff-app/liftoff/issues/149). It creates a new toggle switch controlling the display of post thumbnails in Card View, which also becomes disabled/unselectable when the "Show Thumbnails" setting is disabled. The "PostStyleConfigPage" class had to be converted to a Stateful Widget to do this.

### CODE REVIEW

**Comment by zachatrocity** [comment]
Do we need an option for this? we already know if the user is in card view so we could just not show the thumbnail right?

**Comment by christopher-conley** [comment]
> Do we need an option for this? we already know if the user is in card view so we could just not show the thumbnail right?

I think it makes sense to make it an option, as the current behavior is to display a thumbnail. I think it'd be better to give the user an option as to whether they want it displayed or not because of that, plus it would eliminate the possibility of "Where'd my thumbnail go?" Issues that people might submit if the thumbnail just disappears if it's not an option.

**Comment by zachatrocity** [comment]
Yeah.. it looks pretty ugly with the thumbnail though. 

And we're trying to be conservative with our settings additions because each one adds a condition that can make things tricker in the future.

If you don't mind, let's remove the setting and just check for compact mode.

**Comment by christopher-conley** [comment]
> Yeah.. it looks pretty ugly with the thumbnail though.
> 
> And we're trying to be conservative with our settings additions because each one adds a condition that can make things tricker in the future.
> 
> If you don't mind, let's remove the setting and just check for compact mode.

Done, [Commit 2e1e226](https://github.com/liftoff-app/liftoff/pull/184/commits/2e1e226f0d0c1086d3864e5a9447c434f6280aec)

**Review by zachatrocity — APPROVED** [review]
LGTM

**Pull request merged**
