### PR TITLE
Add delete option to post 3-dot menu

### LINKED ISSUE #124: Add delete button to posts
I can't delete posts on Liftoff. Either from my profile, the community or the post itself.

The triple dot menu should have a delete button.

### PR DESCRIPTION
**Pull request by swmarks**
Fixes #124 

https://github.com/liftoff-app/liftoff/assets/9942801/48c58882-3ad1-4970-9c0a-9356f2fa1d1d

### CODE REVIEW

**Comment by zachatrocity** [comment]
Looks good, however an existing unit test failed, could you take a look?

**Comment by swmarks** [comment]
Not sure what caused the tests to fail last night, but I just updated my branch and it passed now 🤷 

If there's anything I can do to further put it through its paces, I'll definitely give it a go.

**Comment by zachatrocity** [comment]
It was probably all the outages through the night. Looks good

**Review by zachatrocity — APPROVED** [review]
LGTM 👊

**Pull request merged**
