### PR TITLE
Theme and layout changes

### PR DESCRIPTION
**Pull request by swmarks**
This is a WIP

### CODE REVIEW

**Comment by mykdavies** [comment]
Oh this is looking way nicer on the home tab. Thanks for putting this together!

Simulator Screenshot - iPhone 14 Plus 6 5  - 2023-07-09 at 13 34 49
Simulator Screenshot - iPhone 14 Plus 6 5  - 2023-07-09 at 13 35 23

Could you keep a log here of what you've updated? That would save me digging through to code to find out what to look for?

One thing that is very clear already is that if we had the instance at the top, and dropped "Subscribed" down to be with "Hot", that would look even better.
Simulator Screenshot - iPhone 14 Plus 6 5  - 2023-07-09 at 13 40 58

**Comment by zachatrocity** [comment]
Will you fix the borderRadius toggle to complete remove the radius and make border radius off by default? Looks much more sleek

**Comment by zachatrocity** [comment]
Dark: 

image

AMOLED:

image


Light:

image

**Review by zachatrocity — APPROVED** [review]
LGTM 👊

**Pull request merged**
