### PR TITLE
Add shadow to Bottom App Bar

### PR DESCRIPTION
**Pull request by swmarks**
This addresses https://github.com/liftoff-app/liftoff/issues/245

This adds some depth so that there's more to visually distinguish it from the cards below.

Screenshot_20230703_184416

### CODE REVIEW

**Comment by zachatrocity** [comment]
Did you test light mode too? Make sure it's not too intense?

**Comment by swmarks** [comment]
Whoops, yeah, light mode looks good too. I guess it's technically also still there in amoled mode, but you can't tell. 

Screenshot_20230703_192703

**Comment by swmarks** [comment]
I'm actually kind of wondering about trying it with the top bar too, but I'm not sure how that'll layer with the separate pieces

**Comment by jordan1776** [comment]
I like the way the shadows look on the bottom bar. The shadow could look odd on the top since that section looks like it's behind the posts when at the top of the feed, but infront of the posts in the middle. I put together a quick and dirty photoshop in the #245 post about the colorizing idea. Not sure how or if it should carryover to amoled mode, though. What do you think?

**Review by zachatrocity — APPROVED** [review]
LGTM 👊

**Comment by zachatrocity** [comment]
Going to merge, any changes related to coloring would make sense in a separate pr

**Pull request merged**
