### PR TITLE
Adding support for Android 13 themed icons

### PR DESCRIPTION
**Pull request by aquierick**
Screenshot_20230706_235701_One UI Home
SmartSelect_20230706_235732_One UI Home
SmartSelect_20230706_235758_One UI Home

### CODE REVIEW

**Review by swmarks — COMMENTED** [review]
This looks really good to me! I'm going to let @zachatrocity or @mykdavies be the approver, but the app icon has definitely kind of stuck out like a sore thumb in my app drawer and home screen.

**Comment by mykdavies** [comment]
Doesn't touch on the iOS side of things, so fine by me. Looks very nice but I'll leave Zach to approve.

**Review by zachatrocity — APPROVED** [review]
Looks awesome! Thanks for the contribution!

**Comment by aquierick** [comment]
Glad to help!

**Comment by shocklateboy92** [comment]
Since everyone else has already voiced their approval, I'll take the honor of merging it :mermaid: 

Oh btw, how did you make the icon monochrome?

**Comment by aquierick** [comment]
> Oh btw, how did you make the icon monochrome?

Manual process basically. I grabbed the original png one and first removed the background. Then I just used a basic image editor to replace all remaining colors to the same solid grey. From there I just generated the assets for the different dpis and that was it.

**Pull request merged**
