### PR TITLE
Tap to hide comment

### PR DESCRIPTION
**Pull request by Maarten-buelens**
I would like to add the option of tapping a comment to collapse it.

The settings menu works and the tapping also.

But i need some help reading the configstore.
And just a general review. I don't have a lot of experience with dart.

### CODE REVIEW

**Comment by zachatrocity** [comment]
For using the config check out this example for showScores:

```
final showScores = useStore((ConfigStore store) => store.showScores);
```

https://github.com/liftoff-app/liftoff/blob/2738a57ac6af67da49521c902a41d2fe0fa30cc5/lib/widgets/post/post_voting.dart#L18

**Comment by zachatrocity** [comment]
@Maarten-buelens alrighty I just had a good conversation with @mykdavies and scratch everything about the settings.

First, I'm sorry for having you mess with the settings for this. 

We discussed the user experience and we agreed that tap to collapse makes the most sense, and we don't want to give the user the option to use long press on the settings because then we won't be able to use long press for something else in the future.

So new plan:

1. Make tap to collapse the default functionality and remove the long press all together.

2. Scrap the settings changes, you can just delete them. (Sorry, my bad ❤️)

3. Could we mess around with making it clear to the user what has happened and how to undo it? For example right now we show this when a comment is collapsed:  what if instead of the faded text here we put something like: `[Thread collapsed. Tap to expand]`

**Comment by Maarten-buelens** [comment]
Changed onLongPress to onTap.

Its no problem, it was fun learning dart and flutter. I will look if there are some other easy issues.

The collapsed comments should be more clear. I do like how boost did it.
Only showing the username and score.

photo1687864042

**Comment by mykdavies** [comment]
Hey Maarten, could you look at how to display "[Thread collapsed. Tap to expand]" in place of the current approach of showing the first line of the collapsed comment? I'm concerned that if a new user accidentally taps on a comment the whole screen suddenly changes, and it can be confusing to work out what changed and why so a clear message would be helpful here. We can certainly think about how much more compact presentations we can make this once we've got this change in.
Thanks for bearing with us as we start to build our UX principles on the fly here :-)

**Comment by Maarten-buelens** [comment]
Yeah, sure I will look into it.

**Review by zachatrocity — APPROVED** [review]
LGTM!

**Pull request merged**
