### PR TITLE
Re-orientate all photos and use simple crop tool

### PR DESCRIPTION
**Pull request by mykdavies**
All loaded images get their orientation baked in, plus the user now has a chance to crop their chosen image.

### CODE REVIEW

**Comment by mykdavies** [comment]
Needs a check for Android. Should be fine, but I can't actually take or access photos on the Android emulator. The problem it solves is if you take a photo in landscape mode some phones/OS versions hold that orientation in the EXIF data, so when lemmy strips that on upload, the photo ends up sideways. I've just applied the same processing I added for iOS to all photos. 

I also added a simple cropping widget to allow the user to select the area they want (addressing issue #320) and moved the above logic into that widget.

**Comment by zachatrocity** [comment]
There is some bug on Android, getting:



I'm wondering if it could be a missing intent. Will dig into it shortly. This is a great feature

**Comment by mykdavies** [comment]
Ah, well. Thanks for checking so quickly. I might have to hand it over if there's anything tricky going on on that side. Or (grits teeth) get an Android phone for testing :-)

**Review by zachatrocity — APPROVED** [review]
Just validated on Android! Works great! Awesome feature

**Pull request merged**
