### PR TITLE
Option to automatically convert webp images to png

### PR DESCRIPTION
**Pull request by njshockey**
I downloaded a single webp image and I just thought "I've had enough." So I put in an option in the settings to automatically convert them to png. This does add the [image](https://pub.dev/packages/image) dependency and the feature can definitely be improved (it'd be pretty easy to convert to jpg instead) but this should be useful enough to justify turning it on. This doesn't support converting animated webp to gif but I had no idea animated webp even existed before looking at the image package documentation so I doubt it's common enough to worry about.

[Post to test on](https://lemmy.world/post/913665)

[Image link](https://lemmy.ml/pictrs/image/7fb2e92b-fefe-4638-879c-65726dced745.webp)

### CODE REVIEW

**Comment by zachatrocity** [comment]
Is this a very big problem? I've never had the need to do this.

**Review by shocklateboy92 — APPROVED** [review]
I didn't know there were enough desktop users for this to be a problem :astonished:

**Comment by njshockey** [comment]
Alright, I fixed the merge conflict. It was only one line luckily.

**Comment by swmarks** [comment]
I could also see this potentially being useful down the line for sharing compatibility if another app we try to share an image with doesn't support webp natively

**Pull request merged**
